export const stockFixed = {
  'shippedOrderDate': '出仓订单日期',
  'shippedDate': '实际离仓日期',
  'shippedNo': '出仓单号',
  'so': '入仓落货纸号',
  'op': '客户采购订单号',
  'sku': '货物款号',
  'shippedCtns': '总出仓箱数',
  'shippedPcs': '出仓件数',
  'warehousePosition': '仓库位置',
  'shippedGw': '出仓毛重',
  'shippedVolume': '出仓体积',
  'inboundNo': '入仓编号',
  'customsMeterialNo': '海关系统物料号',
  'customsMerchNo': '商品编码',
  'merchName': '商品名称',
  'declaCount': '成交数量',
  'declaUnit': '成交单位',
  'declaUnitPrice': '成交单价',
  'declaTotalPrice': '成交总价',
  'declaCurrency': '成交币种',
  'originCountry': '原产国',
  'destCountry': '目的国',
  'pieceWeigh': '单件净重',
  'shippedAllWeigh': '出仓总净重'
}
